[tool.poetry]
name = "nurse"
version = "2.1.0"
description = "A thoughtful dependency injection framework"
authors = ["ducdetronquito <g.paulet@zero-gachis.com>"]
readme = "README.md"
repository = "https://github.com/ZeroGachis/nurse"
homepage = "https://github.com/ZeroGachis/nurse"
keywords = ["dependency", "injection"]

[tool.poetry.dependencies]
python = "~3.13"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0"
ruff = "^0.15"
pre-commit = "^4"
basedpyright = "^1.37"

[tool.poetry.group.ci]
optional = true

[tool.poetry.group.ci.dependencies]
pytest-github-actions-annotate-failures = "^0.3.0"
pytest-cov = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--disable-plugin-autoload",
]
pythonpath = "./"

[tool.coverage.run]
branch = true
relative_files = true
source = ["nurse"]

[tool.ruff]
# Use black default line length to avoid to many changes at first
line-length = 88
# It would be preferable to use python's standard "project.requires-python"
# but poetry does not comply with it.
target-version = "py313"

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"
include = ["nurse/**"]
exclude = ["**/__pycache__"]

executionEnvironments = [{ root = "nurse" }]
