name: "PullRequest-Push"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"

jobs:

  releasetag:
    uses: ZeroGachis/.github/.github/workflows/releasetag.yml@v4
    permissions:
      contents: read

  build:
    needs: releasetag
    uses: ZeroGachis/.github/.github/workflows/build-image.yml@v4
    permissions:
      actions: read
      checks: write
      contents: read
      id-token: write
      packages: write
      pull-requests: write
      security-events: write
    with:
      image_name: nurse
      dockerfile_context: .
      vault_enabled: false
      tailscale_enabled: false
      regitry_url: ghcr.io
    secrets: inherit

  static-metrics:
    needs:
      [
        build,
      ]
    uses: ZeroGachis/.github/.github/workflows/run-docker.yml@v4
    permissions:
      contents: read
      id-token: write
      packages: read
      actions: write
      checks: write
    with:
      image_url: ${{ needs.build.outputs.image-url }}
      tailscale_enabled: false
      vault_enabled: false
      workdir: /app
      run_command: |
        ruff check --diff ./
        ruff format --check --diff ./
    secrets: inherit

  unit-tests:
    needs:
      [
        build,
      ]
    uses: ZeroGachis/.github/.github/workflows/run-pytest.yml@v4
    permissions:
        actions: write
        checks: write
        contents: write
        id-token: write
        packages: read
        pull-requests: write
    with:
      image_url: ${{ needs.build.outputs.image-url }}
      workdir: /app
      directory_to_test: tests/
      env_django_settings_module: todo-make-this-optional
    secrets: inherit

  destroy:
    if: always()
    needs:
      [
        releasetag,
        build,
        unit-tests,
        static-metrics,
      ]
    uses: ZeroGachis/.github/.github/workflows/delete-docker-image.yml@v1
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      image_name: nurse
      image_version: ${{ needs.build.outputs.image-version }}
    secrets: inherit
