name: "Release"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-release:
    uses: ZeroGachis/.github/.github/workflows/gh-release-please.yml@v4
    with:
        major_and_minor_tags: false
  publish:
    needs: github-release
    if: ${{ needs.github-release.outputs.release_created == 'true' }}
    uses: ZeroGachis/.github/.github/workflows/python-publish.yml@v4
    with:
      python_version: "3.12"
      environment_name: main
