name: "Release"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    uses: ZeroGachis/.github/.github/workflows/build-image.yml@v3
    with:
      image_name: nurse
      dockerfile_context: .
      regitry_url: ghcr.io
      build-args: |
        REQUIREMENTS=dev
    secrets: inherit

  static-metrics:
    needs: 
      [
        build, 
      ]
    uses: ZeroGachis/.github/.github/workflows/run-docker.yml@v3
    with:
      image_url: ${{ needs.build.outputs.image-url }}
      workdir: /home/src/nurse
      run_command: |
        flake8 .
    secrets: inherit

  unit-tests:
    needs: 
      [
        build, 
      ]
    uses: ZeroGachis/.github/.github/workflows/run-docker-with-db.yml@v3
    with:
      image_url: ${{ needs.build.outputs.image-url }}
      workdir: /home/src/nurse
      run_command: |
        pytest --verbose
      enable_test_report: false
    secrets: inherit

  push:
    needs: 
      [
        build, 
        unit-tests,
        static-metrics,
      ]
    uses: ZeroGachis/.github/.github/workflows/push-pypi.yml@v3
    with:
      image_url: ${{ needs.build.outputs.image-url }}
      workdir: /home/src/nurse
    secrets: inherit

  detroy:
    if: always()
    needs:
      [
        build,
        unit-tests,
        static-metrics,
      ]
    uses: ZeroGachis/.github/.github/workflows/delete-docker-image.yml@v3
    with:
      image_name: nurse
      image_version: ${{ needs.build.outputs.image-version }}
    secrets: inherit
